// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NyanCatMiner) DeepCopyInto(out *NyanCatMiner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NyanCatMiner.
func (in *NyanCatMiner) DeepCopy() *NyanCatMiner {
	if in == nil {
		return nil
	}
	out := new(NyanCatMiner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NyanCatMiner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NyanCatMinerList) DeepCopyInto(out *NyanCatMinerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NyanCatMiner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NyanCatMinerList.
func (in *NyanCatMinerList) DeepCopy() *NyanCatMinerList {
	if in == nil {
		return nil
	}
	out := new(NyanCatMinerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NyanCatMinerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NyanCatMinerSpec) DeepCopyInto(out *NyanCatMinerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NyanCatMinerSpec.
func (in *NyanCatMinerSpec) DeepCopy() *NyanCatMinerSpec {
	if in == nil {
		return nil
	}
	out := new(NyanCatMinerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NyanCatMinerStatus) DeepCopyInto(out *NyanCatMinerStatus) {
	*out = *in
	if in.PodNames != nil {
		in, out := &in.PodNames, &out.PodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NyanCatMinerStatus.
func (in *NyanCatMinerStatus) DeepCopy() *NyanCatMinerStatus {
	if in == nil {
		return nil
	}
	out := new(NyanCatMinerStatus)
	in.DeepCopyInto(out)
	return out
}
